/* =========================================
   JOVA NIGERIA LOCATION DATABASE
   Country → State/FCT → Area → Estate → Address
========================================= */

window.JOVA_LOCATIONS = {

  country: "Nigeria",

  regions: {
    "North Central": [
      "Benue",
      "Kogi",
      "Kwara",
      "Nasarawa",
      "Niger",
      "Plateau",
      "Federal Capital Territory (FCT)"
    ],

    "North East": [
      "Adamawa",
      "Bauchi",
      "Borno",
      "Gombe",
      "Taraba",
      "Yobe"
    ],

    "North West": [
      "Jigawa",
      "Kaduna",
      "Kano",
      "Katsina",
      "Kebbi",
      "Sokoto",
      "Zamfara"
    ],

    "South East": [
      "Abia",
      "Anambra",
      "Ebonyi",
      "Enugu",
      "Imo"
    ],

    "South South": [
      "Akwa Ibom",
      "Bayelsa",
      "Cross River",
      "Delta",
      "Edo",
      "Rivers"
    ],

    "South West": [
      "Ekiti",
      "Lagos",
      "Ogun",
      "Ondo",
      "Osun",
      "Oyo"
    ]
  },

  states: [
    "Abia",
    "Adamawa",
    "Akwa Ibom",
    "Anambra",
    "Bauchi",
    "Bayelsa",
    "Benue",
    "Borno",
    "Cross River",
    "Delta",
    "Ebonyi",
    "Edo",
    "Ekiti",
    "Enugu",
    "Gombe",
    "Imo",
    "Jigawa",
    "Kaduna",
    "Kano",
    "Katsina",
    "Kebbi",
    "Kogi",
    "Kwara",
    "Lagos",
    "Nasarawa",
    "Niger",
    "Ogun",
    "Ondo",
    "Osun",
    "Oyo",
    "Plateau",
    "Rivers",
    "Sokoto",
    "Taraba",
    "Yobe",
    "Zamfara",
    "Federal Capital Territory (FCT)"
  ],

  /*
    Existing neighbourhood data.
    We will expand this database to cover
    LGAs, areas and estates nationwide.
  */

  areasByState: {

    "Lagos": [
      "Lekki",
      "Lekki Phase 1",
      "Lekki Phase 2",
      "Ikoyi",
      "Old Ikoyi",
      "Parkview Estate",
      "Banana Island",
      "Victoria Island",
      "Oniru",
      "Eko Atlantic",
      "Dolphin Estate",
      "Obalende",
      "Falomo",
      "Ajah",
      "Sangotedo",
      "Abijo",
      "Lakowe",
      "Ibeju-Lekki",
      "Awoyaya",
      "Bogije",
      "Eleko",
      "Akodo",
      "Epe",
      "Chevron",
      "VGC",
      "Osapa London",
      "Agungi",
      "Jakande",
      "Ikate",
      "Igbo Efon",
      "Orchid Road",
      "Thomas Estate",
      "Abraham Adesanya",
      "Shoreline Estate",
      "Mayfair Gardens",
      "Ikeja",
      "Ikeja GRA",
      "Alausa",
      "Opebi",
      "Allen Avenue",
      "Maryland",
      "Anthony",
      "Magodo",
      "Magodo Phase 1",
      "Magodo Phase 2",
      "Yaba",
      "Onike",
      "Akoka",
      "Sabo",
      "Jibowu",
      "Ebute Metta",
      "Surulere",
      "Aguda",
      "Ojuelegba",
      "Lawanson",
      "Itire",
      "Ijeshatedo",
      "Mushin",
      "Palm Avenue",
      "Gbagada",
      "Anthony Village",
      "Ketu",
      "Alapere",
      "Ojota",
      "Ogudu",
      "Ogudu GRA",
      "Kosofe",
      "Oworonshoki",
      "Agege",
      "Ogba",
      "Ifako-Ijaiye",
      "Iju",
      "Fagba",
      "Iyana Ipaja",
      "Alimosho",
      "Egbeda",
      "Akowonjo",
      "Idimu",
      "Isolo",
      "Ejigbo",
      "Ikotun",
      "Igando",
      "Festac",
      "Amuwo Odofin",
      "Mile 2",
      "Satellite Town",
      "Orile",
      "Ojo",
      "Alaba",
      "Iyana Iba",
      "Badagry",
      "Ikorodu",
      "Ipakodo",
      "Agric",
      "Igbogbo",
      "Imota",
      "Ketu-Epe",
      "Lagos Island",
      "Idumota",
      "Marina",
      "Broad Street",
      "Oyingbo",
      "Costain",
      "Iwaya",
      "Makoko",
      "Bariga",
      "Shomolu",
      "Palmgrove",
      "Fadeyi"
    ],

    "Federal Capital Territory (FCT)": [
      "Maitama",
      "Wuse",
      "Wuse 2",
      "Asokoro",
      "Garki",
      "Gwarinpa",
      "Jabi",
      "Life Camp",
      "Katampe",
      "Lugbe",
      "Kubwa",
      "Utako",
      "Karu",
      "Kado",
      "Apo",
      "Galadimawa",
      "Guzape",
      "Lokogoma",
      "Durumi",
      "Central Area",
      "Mabushi",
      "Karsana",
      "Dakibiyu",
      "Jahi",
      "Karmo",
      "Dei-Dei",
      "Dutse",
      "Bwari",
      "Kuje",
      "Nyanya",
      "Airport Road",
      "Gwarinpa Estate"
    ],

    "Rivers": [
      "Port Harcourt",
      "GRA",
      "Old GRA",
      "New GRA",
      "Trans Amadi",
      "Woji",
      "Rumuola",
      "Rumuokoro",
      "Rumueme",
      "Rumuodara",
      "Eliozu",
      "Ada George",
      "Abonnema Wharf",
      "Peter Odili Road",
      "Choba",
      "Omagwa",
      "D-Line",
      "Old Township",
      "New Layout",
      "Mile 1",
      "Mile 2",
      "Mile 3",
      "Mile 4",
      "Mile 5",
      "Diobu",
      "Rumuomasi",
      "Rumuigbo",
      "Rumuokwuta",
      "Rukpokwu",
      "Borokiri",
      "Oginigba",
      "Amadi Flat",
      "Elekahia",
      "Nkpogu",
      "Rainbow Town",
      "Iwofe",
      "Aluu",
      "Ozuoba"
    ]

  },

  /*
    Future address fields.
    These will be connected to the listing form.
  */

  addressFields: [
    "state",
    "lga",
    "area",
    "estate",
    "street",
    "buildingNumber",
    "fullAddress"
  ]

};
